//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace uEN.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uEN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add to Favourites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddToFavourites {
            get {
                return ResourceManager.GetString("AddToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced Configuration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdvancedConfiguration {
            get {
                return ResourceManager.GetString("AdvancedConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alternately accents add color line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AlternatingColor {
            get {
                return ResourceManager.GetString("AlternatingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Asynchronous display(Performance improvement) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AsynchronousDisplay {
            get {
                return ResourceManager.GetString("AsynchronousDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brand Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrandColor {
            get {
                return ResourceManager.GetString("BrandColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DarkColor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DarkColor {
            get {
                return ResourceManager.GetString("DarkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Family に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Glass(Brand Color) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Glass_Brand {
            get {
                return ResourceManager.GetString("Glass_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Glass Blue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GlassBlue {
            get {
                return ResourceManager.GetString("GlassBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GlassGreen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GlassGreen {
            get {
                return ResourceManager.GetString("GlassGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Glass Red に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GlassRed {
            get {
                return ResourceManager.GetString("GlassRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Glass Yellow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GlassYellow {
            get {
                return ResourceManager.GetString("GlassYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grid Configuration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GridConfiguration {
            get {
                return ResourceManager.GetString("GridConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputRequired {
            get {
                return ResourceManager.GetString("InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LightColor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LightColor {
            get {
                return ResourceManager.GetString("LightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove from Favorites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveToFavourites {
            get {
                return ResourceManager.GetString("RemoveToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeColorView_Title {
            get {
                return ResourceManager.GetString("ThemeColorView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeColorViewModel_Title {
            get {
                return ResourceManager.GetString("ThemeColorViewModel_Title", resourceCulture);
            }
        }
    }
}
